# Generated by Django 5.0.6 on 2024-06-23 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
